language: go
go:
  - 1.11.x
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
git:
  depth: 3
branches:
  only:
    - master
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
    else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export TAG=$(if [ -n "$TRAVIS_TAG" ]; then echo $TRAVIS_TAG; else echo $BRANCH;
    fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, TAG=$TAG"
script:
  - go test ./... --count 1
deploy:
  - provider: script
    script: bash deploy.sh
    on:
      branch:  master
