// Code generated by GoJay. DO NOT EDIT.

package user

import (
	"github.com/francoispqt/gojay"
	uuid "github.com/satori/go.uuid"
)

// UnmarshalJSONObject implements gojay's UnmarshalerJSONObject
func (v *User) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {
	switch k {
	case "id":
		var u string
		err := dec.String(&u)
		v.ID = uuid.FromStringOrNil(u)
		return err
	case "username":
		return dec.String(&v.Username)
	}
	return nil
}

// NKeys returns the number of keys to unmarshal
func (v *User) NKeys() int { return 2 }

// MarshalJSONObject implements gojay's MarshalerJSONObject
func (v *User) MarshalJSONObject(enc *gojay.Encoder) {
	enc.StringKey("id", v.ID.String())
	enc.StringKey("username", v.Username)
	enc.StringKey("password", v.Password)
}

// IsNil returns wether the structure is nil value or not
func (v *User) IsNil() bool { return v == nil }
