// Code generated by GoJay. DO NOT EDIT.

package user 

import "github.com/francoispqt/gojay"

// UnmarshalJSONObject implements gojay's UnmarshalerJSONObject
func (v *createUserRequest) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {
	switch k {
	case "username":
		return dec.String(&v.Username)
	case "password":
		return dec.String(&v.Password)
	}
	return nil
}

// NKeys returns the number of keys to unmarshal
func (v *createUserRequest) NKeys() int { return 2 }

// MarshalJSONObject implements gojay's MarshalerJSONObject
func (v *createUserRequest) MarshalJSONObject(enc *gojay.Encoder) {
	enc.StringKey("username", v.Username)
	enc.StringKey("password", v.Password)
}

// IsNil returns wether the structure is nil value or not
func (v *createUserRequest) IsNil() bool { return v == nil }
