apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: project-b
    app: project-b-backed
    env: production
    service: http
  name: project-b-backed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: http
      app: project-b-backed
      project: project-b
      env: production
  template:
    metadata:
      labels:
        project: project-b
        app: project-b-backed
        env: production
        service: http
    spec:
      containers:
        - name: project-b-backed
          image: ogkevin/project-b-backend
          command: ["/http"]
          resources:
            limits:
              cpu: "10m"
              memory: "50Mi"
          envFrom:
            - configMapRef:
                name: project-b-backed-env
            - secretRef:
                name: project-b-backed-sec-env
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 5
      imagePullSecrets:
        - name: dockercred
