apiVersion: v1
kind: Service
metadata:
  name: project-b-backend-http
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 80
      port: 60000
  selector:
    project: project-b
    app: project-b-backed
    env: production
    service: http
