// Code generated by GoJay. DO NOT EDIT.

package responses 

import "github.com/francoispqt/gojay"

// UnmarshalJSONObject implements gojay's UnmarshalerJSONObject
func (v *NotFound) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {
	switch k {
	case "ack":
		return dec.Object(&v.Ack)
	}
	return nil
}

// NKeys returns the number of keys to unmarshal
func (v *NotFound) NKeys() int { return 0 }

// MarshalJSONObject implements gojay's MarshalerJSONObject
func (v *NotFound) MarshalJSONObject(enc *gojay.Encoder) {
	enc.ObjectKey("ack", &v.Ack)
}

// IsNil returns wether the structure is nil value or not
func (v *NotFound) IsNil() bool { return v == nil }
