// Code generated by GoJay. DO NOT EDIT.

package responses

import (
	"github.com/francoispqt/gojay"
	uuid "github.com/satori/go.uuid"
)

// UnmarshalJSONObject implements gojay's UnmarshalerJSONObject
func (v *Created) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {
	switch k {
	case "ack":
		return dec.Object(&v.Ack)
	case "id":
		var u string
		err := dec.String(&u)
		v.ID = uuid.FromStringOrNil(u)
		return err
	}
	return nil
}

// NKeys returns the number of keys to unmarshal
func (v *Created) NKeys() int { return 1 }

// MarshalJSONObject implements gojay's MarshalerJSONObject
func (v *Created) MarshalJSONObject(enc *gojay.Encoder) {
	enc.ObjectKey("ack", &v.Ack)
	enc.StringKey("id", v.ID.String())
}

// IsNil returns wether the structure is nil value or not
func (v *Created) IsNil() bool { return v == nil }
