// Code generated by GoJay. DO NOT EDIT.

package responses 

import "github.com/francoispqt/gojay"

// UnmarshalJSONObject implements gojay's UnmarshalerJSONObject
func (v *Ack) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {
	switch k {
	case "ack":
		return dec.Bool(&v.Ack)
	}
	return nil
}

// NKeys returns the number of keys to unmarshal
func (v *Ack) NKeys() int { return 1 }

// MarshalJSONObject implements gojay's MarshalerJSONObject
func (v *Ack) MarshalJSONObject(enc *gojay.Encoder) {
	enc.BoolKey("ack", v.Ack)
}

// IsNil returns wether the structure is nil value or not
func (v *Ack) IsNil() bool { return v == nil }
