apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: project-b
spec:
  rules:
    - host: project-b.ogkevin.nl
      http:
        paths:
          - path: /
            backend:
              serviceName: project-b-backend-http
              servicePort: 60000
  tls:
    - hosts:
      - project-b.ogkevin.nl
      secretName: project-b-ogkevin-nl-cert
